const EN = {
  label: 'Create a Lesson', prompt: 'Teach me what this video explains through clear objectives, guided modules, checkpoint questions, and a final application exercise.',
  objectives: 'Learning objectives', prerequisites: 'Before you start', readiness: 'Readiness check', modules: 'Your learning path', milestone: 'Milestone', example: 'Worked example', video: 'From the video', generated: 'Generated practice example', questions: 'Check your understanding', challenge: 'Final application challenge', review: 'Come back and recall', gaps: 'Limits of this lesson', hint: 'Show a hint', answer: 'Reveal answer and explanation', criteria: 'Success criteria', response: 'Your response', checked: 'I compared my response with the criteria', progress: 'Checkpoints reviewed', storage: 'Responses and progress save only in this browser. They are not synced to your account. Review marks are self-assessment, not verified mastery.', unavailable: 'This browser could not save your progress. Keep a separate copy of your responses.', student: 'Student worksheet', key: 'Answer key', note: 'Questions and exercises are generated from the cited teaching. Source claims have not been independently verified.', noLesson: 'There is not enough supported teaching to create a complete lesson. Try a video that explains a concept or demonstrates a skill.', reset: 'Reset study progress', recall: 'Recall', explain: 'Explain why', apply: 'Apply', export: 'Download', level: 'Suggested level', links: 'Supporting video', worksheet: 'Write your response here.'
};
export type LessonCopy = typeof EN;
const copies: Record<string, Partial<LessonCopy>> = {
  'zh-CN': {label:'创建课程',prompt:'把视频讲解转成有学习目标、分步模块、检查问题和最终应用练习的课程。',objectives:'学习目标',prerequisites:'开始前',readiness:'准备检查',modules:'学习路径',milestone:'里程碑',example:'示例讲解',video:'来自视频',generated:'生成的练习示例',questions:'检查理解',challenge:'最终应用练习',review:'稍后回忆复习',gaps:'课程局限',hint:'查看提示',answer:'显示答案与解释',criteria:'成功标准',response:'你的回答',checked:'我已对照标准检查回答',progress:'已检查的问题',storage:'回答和进度仅保存在此浏览器，不与账户同步。标记为自我评估，不代表已掌握。',unavailable:'浏览器无法保存进度，请另行保存回答。',student:'学生练习单',key:'答案指南',note:'问题和练习根据所引用的教学内容生成。来源中的主张未独立验证。',noLesson:'没有足够的教学依据生成完整课程，请选择讲解概念或演示技能的视频。',reset:'重置学习进度',recall:'回忆',explain:'解释原因',apply:'应用',export:'下载',level:'建议程度',links:'支持内容的视频',worksheet:'在此填写回答。'},
  'zh-TW': {label:'建立課程',prompt:'將影片講解轉成有學習目標、引導模組、檢查問題和最終應用練習的課程。',objectives:'學習目標',prerequisites:'開始之前',readiness:'準備檢查',modules:'學習路徑',milestone:'里程碑',example:'範例講解',video:'來自影片',generated:'產生的練習範例',questions:'檢查理解',challenge:'最終應用練習',review:'稍後回想複習',gaps:'課程限制',hint:'查看提示',answer:'顯示答案與解釋',criteria:'成功標準',response:'你的回答',checked:'我已對照標準檢查回答',progress:'已檢查的問題',storage:'回答和進度只儲存在此瀏覽器，不與帳戶同步。標記是自我評估，不代表已掌握。',unavailable:'瀏覽器無法儲存進度，請另行保存回答。',student:'學生練習單',key:'答案指南',note:'問題和練習依據引用的教學內容產生。來源中的主張未獨立驗證。',noLesson:'沒有足夠的教學依據建立完整課程，請選擇講解概念或示範技能的影片。',reset:'重設學習進度',recall:'回想',explain:'解釋原因',apply:'應用',export:'下載',level:'建議程度',links:'支持內容的影片',worksheet:'在此填寫回答。'},
  es: {label:'Crear una lección',prompt:'Convierte lo que enseña este video en una lección con objetivos, módulos guiados, preguntas y un ejercicio final.',objectives:'Objetivos de aprendizaje',prerequisites:'Antes de empezar',readiness:'Comprueba tu preparación',modules:'Tu ruta de aprendizaje',milestone:'Hito',example:'Ejemplo explicado',video:'Del video',generated:'Ejemplo de práctica generado',questions:'Comprueba tu comprensión',challenge:'Ejercicio final de aplicación',review:'Repasa de memoria más adelante',gaps:'Límites de la lección',hint:'Mostrar una pista',answer:'Revelar respuesta y explicación',criteria:'Criterios de éxito',response:'Tu respuesta',checked:'Comparé mi respuesta con los criterios',progress:'Preguntas revisadas',storage:'Las respuestas y el progreso se guardan solo en este navegador, sin sincronizarse con tu cuenta. Las marcas son autoevaluaciones, no dominio verificado.',unavailable:'El navegador no pudo guardar el progreso. Guarda tus respuestas por separado.',student:'Hoja del estudiante',key:'Guía de respuestas',note:'Las preguntas y los ejercicios se generan a partir de la enseñanza citada. Las afirmaciones de la fuente no se han verificado de forma independiente.',noLesson:'No hay suficiente enseñanza respaldada para crear una lección completa. Prueba un video que explique un concepto o demuestre una habilidad.',reset:'Restablecer progreso',recall:'Recordar',explain:'Explicar por qué',apply:'Aplicar',export:'Descargar',level:'Nivel sugerido',links:'Video de referencia',worksheet:'Escribe tu respuesta aquí.'},
  ro: {label:'Creează o lecție',prompt:'Transformă explicațiile din videoclip într-o lecție cu obiective, module, întrebări și un exercițiu final.',objectives:'Obiective de învățare',prerequisites:'Înainte de a începe',readiness:'Verificarea pregătirii',modules:'Parcursul tău',milestone:'Etapă',example:'Exemplu explicat',video:'Din videoclip',generated:'Exemplu de practică generat',questions:'Verifică înțelegerea',challenge:'Exercițiu final de aplicare',review:'Revino și amintește-ți',gaps:'Limitele lecției',hint:'Arată un indiciu',answer:'Arată răspunsul și explicația',criteria:'Criterii de reușită',response:'Răspunsul tău',checked:'Mi-am comparat răspunsul cu criteriile',progress:'Întrebări revizuite',storage:'Răspunsurile și progresul se salvează doar în acest browser, fără sincronizare cu contul. Bifele reprezintă autoevaluare, nu competență verificată.',unavailable:'Browserul nu a putut salva progresul. Păstrează separat răspunsurile.',student:'Fișă pentru cursant',key:'Ghid de răspunsuri',note:'Întrebările și exercițiile sunt generate pe baza explicațiilor citate. Afirmațiile sursei nu sunt verificate independent.',noLesson:'Nu există suficiente explicații pentru o lecție completă. Încearcă un videoclip care explică un concept sau demonstrează o abilitate.',reset:'Resetează progresul',recall:'Amintește-ți',explain:'Explică de ce',apply:'Aplică',export:'Descarcă',level:'Nivel sugerat',links:'Videoclip de referință',worksheet:'Scrie răspunsul aici.'},
  hi: {label:'पाठ बनाएं',prompt:'वीडियो की शिक्षा को उद्देश्यों, निर्देशित भागों, प्रश्नों और अंतिम अभ्यास वाले पाठ में बदलें।',objectives:'सीखने के उद्देश्य',prerequisites:'शुरू करने से पहले',readiness:'तैयारी की जांच',modules:'सीखने का मार्ग',milestone:'पड़ाव',example:'समझाया गया उदाहरण',video:'वीडियो से',generated:'बनाया गया अभ्यास उदाहरण',questions:'अपनी समझ जांचें',challenge:'अंतिम प्रयोग अभ्यास',review:'बाद में याद करके दोहराएं',gaps:'पाठ की सीमाएं',hint:'संकेत दिखाएं',answer:'उत्तर और व्याख्या देखें',criteria:'सफलता के मानदंड',response:'आपका उत्तर',checked:'मैंने उत्तर का मानदंडों से मिलान किया',progress:'समीक्षित प्रश्न',storage:'उत्तर और प्रगति केवल इस ब्राउज़र में सहेजे जाते हैं, खाते से सिंक नहीं होते। निशान स्व-मूल्यांकन हैं, प्रमाणित महारत नहीं।',unavailable:'ब्राउज़र प्रगति नहीं सहेज सका। उत्तर अलग से सुरक्षित करें।',student:'विद्यार्थी कार्यपत्रक',key:'उत्तर मार्गदर्शिका',note:'प्रश्न और अभ्यास उद्धृत शिक्षा से बनाए गए हैं। स्रोत के दावों की स्वतंत्र पुष्टि नहीं की गई है।',noLesson:'पूरा पाठ बनाने के लिए पर्याप्त शिक्षण सामग्री नहीं है। अवधारणा समझाने या कौशल दिखाने वाला वीडियो आज़माएं।',reset:'प्रगति रीसेट करें',recall:'याद करें',explain:'कारण बताएं',apply:'प्रयोग करें',export:'डाउनलोड',level:'सुझाया स्तर',links:'संदर्भ वीडियो',worksheet:'यहां अपना उत्तर लिखें।'},
};
export function lessonCopy(language?: string | null): LessonCopy {
  const tag=(language||'en').replace(/_/g,'-');
  const key=/^zh-(TW|HK|Hant)/i.test(tag)?'zh-TW':/^zh/i.test(tag)?'zh-CN':tag.split('-')[0];
  return {...EN,...copies[key]};
}
