import { normalizeProcedure, type ProcedureFact } from './procedure.js';
import { procedureCopy } from './procedureCopy.js';
import { safeRecipeUrl } from './recipe.js';
const esc = (s: string) => s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]!);
const stamp = (t: number) => `${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
export function procedureTimestampUrl(source: string | null, t: number): string | null {
  const safe = safeRecipeUrl(source); if (!safe) return null;
  const u = new URL(safe);
  if (!/(^|\.)(youtube\.com|youtu\.be)$/.test(u.hostname)) return null;
  const id = u.hostname === 'youtu.be' ? u.pathname.slice(1) : /^\/(shorts|embed)\//.test(u.pathname) ? u.pathname.split('/')[2] : u.searchParams.get('v');
  return id ? `https://www.youtube.com/watch?v=${encodeURIComponent(id)}&t=${Math.floor(t)}s` : null;
}
export function procedureHtml(value: unknown, language?: string | null, source: string | null = null, duration: number | null = null): string {
  const p=normalizeProcedure(value,duration); if(!p) return ''; const c=procedureCopy(language);
  const fact=(f:ProcedureFact)=>`<div class="procedure-fact"><span class="procedure-value">${esc(f.value??c.unknown)}</span> <span class="procedure-basis procedure-${f.basis}">${esc(c[f.basis])}</span>${f.timestamps.map(t=>{const url=procedureTimestampUrl(source,t);return url?` <a href="${esc(url)}" target="_blank" rel="noopener noreferrer" class="procedure-cite">${stamp(t)} ↗</a>`:` <span class="procedure-cite">${stamp(t)}</span>`;}).join('')}${f.note?`<p class="procedure-note">${esc(f.note)}</p>`:''}</div>`;
  return `<section class="procedure-card" aria-label="${esc(c.procedure)}"><div class="procedure-kicker">${esc(c.procedure)}</div><h2>${esc(p.title)}</h2><p class="procedure-review">${esc(c.review)}</p><h3>${esc(c.outcome)}</h3>${fact(p.outcome)}${p.environment.length?`<h3>${esc(c.environment)}</h3><ul>${p.environment.map(f=>`<li>${fact(f)}</li>`).join('')}</ul>`:''}<h3>${esc(c.prerequisites)}</h3>${p.prerequisites.length?`<ul>${p.prerequisites.map(f=>`<li>${fact(f)}</li>`).join('')}</ul>`:`<p>${esc(c.unknown)}</p>`}
  ${p.gaps.length?`<aside class="procedure-gaps"><h3>${esc(c.gaps)}</h3><ul>${p.gaps.map(g=>`<li>${esc(g)}</li>`).join('')}</ul></aside>`:''}
  <h3>${esc(c.steps)}</h3><ol class="procedure-steps">${p.steps.map(s=>`<li>${fact(s.action)}${s.details.length?`<dl class="procedure-details">${s.details.map(d=>`<div><dt>${esc(d.label)}</dt><dd>${fact(d.value)}</dd></div>`).join('')}</dl>`:''}<div class="procedure-check"><h4>${esc(c.check)}</h4>${fact(s.check)}</div></li>`).join('')}</ol>
  <h3>${esc(c.checklist)}</h3><p class="procedure-note">${esc(c.checklistHelp)}</p><ul class="procedure-checklist">${p.steps.map((s,i)=>`<li><label><input type="checkbox"><span>${i+1}. ${esc(s.action.value??c.unknown)}</span></label></li>`).join('')}</ul></section>`;
}
export function procedureMarkdown(value: unknown, language?: string | null, source: string | null = null): string {
  const p=normalizeProcedure(value);if(!p)return '';const c=procedureCopy(language);
  const f=(v:ProcedureFact)=>`${v.value??c.unknown} (${c[v.basis]})${v.timestamps.map(t=>{const url=procedureTimestampUrl(source,t);return url?` [${stamp(t)}](<${url}>)`:` [${stamp(t)}]`;}).join('')}${v.note?` — ${v.note}`:''}`;
  return [`## ${c.procedure}: ${p.title}`,'',c.review,'',`### ${c.outcome}`,'',f(p.outcome),'',`### ${c.environment}`,'',...p.environment.map(v=>`- ${f(v)}`),'',`### ${c.prerequisites}`,'',...(p.prerequisites.length?p.prerequisites.map(v=>`- ${f(v)}`):[c.unknown]),'',...(p.gaps.length?[`### ${c.gaps}`,'',...p.gaps.map(g=>`- ${g}`),'']:[]),`### ${c.steps}`,'',...p.steps.flatMap((s,i)=>[`${i+1}. ${f(s.action)}`,...s.details.map(d=>`   - ${d.label}: ${f(d.value).replace(/\n/g,'\n     ')}`),`   - ${c.check}: ${f(s.check)}`,'']),`### ${c.checklist}`,'',...p.steps.map(s=>`- [ ] ${s.action.value??c.unknown}`),''].join('\n');
}
export function procedureChecklist(value: unknown, language?: string | null): string {
  const p=normalizeProcedure(value); if(!p) return ''; const c=procedureCopy(language);
  return [p.title, '', ...p.steps.map(s=>`- [ ] ${s.action.value??c.unknown}`)].join('\n');
}
export const PROCEDURE_CSS=`
.procedure-card{box-sizing:border-box;margin:24px 0;padding:24px;border:1px solid #b6cfd8;border-radius:16px;background:#f8fcfd;color:#18363e;overflow-wrap:anywhere;font:inherit}.procedure-card *{box-sizing:border-box}.procedure-kicker{color:#256777;font-size:11px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.procedure-card h2{font-size:27px;line-height:1.25;margin:10px 0 16px}.procedure-card h3{font-size:18px;margin:26px 0 12px;color:#18363e}.procedure-card h4{font-size:12px;margin:0 0 6px;color:#42636c}.procedure-review,.procedure-note{font-size:13px;line-height:1.6;color:#47646d}.procedure-review{border-left:3px solid #73adba;padding-left:12px}.procedure-note{margin:5px 0 0}.procedure-fact{font-size:15px;line-height:1.65;white-space:pre-wrap}.procedure-basis{display:inline-block;font-size:10px;line-height:1.5;padding:2px 6px;border-radius:4px;background:#e2f0f2;color:#275b64;white-space:normal}.procedure-inferred,.procedure-unknown{background:#fff0ce;color:#775215}.procedure-cite{font-size:12px;color:#176479;text-decoration:underline;white-space:nowrap}.procedure-card ul{padding-left:22px}.procedure-card li{margin:9px 0}.procedure-steps{padding-left:24px}.procedure-steps>li{padding:8px 0 20px 8px;border-bottom:1px solid #d5e3e6;break-inside:avoid}.procedure-steps>li::marker{font-weight:800;color:#256777}.procedure-steps>li>.procedure-fact>.procedure-value{font-weight:700}.procedure-details{margin:14px 0;background:#edf4f6;border-radius:8px;padding:12px}.procedure-details>div+div{margin-top:14px}.procedure-details dt{font-size:12px;font-weight:700;color:#41616a;margin-bottom:5px}.procedure-details dd{margin:0}.procedure-details .procedure-value{font-family:ui-monospace,monospace;font-size:13px}.procedure-check{padding:12px;border-left:2px solid #8bb6bd;margin-top:12px}.procedure-gaps{padding:1px 16px 12px;background:#fff5df;border-radius:10px;margin-top:20px}.procedure-gaps h3{margin-top:15px}.procedure-checklist{list-style:none!important;padding:0!important}.procedure-checklist label{display:flex;align-items:flex-start;gap:12px;cursor:pointer;line-height:1.6;padding:8px 0}.procedure-checklist input{appearance:auto!important;width:18px!important;height:18px!important;flex:0 0 18px;margin:4px 0 0!important;accent-color:#176479}.procedure-checklist input:checked+span{text-decoration:line-through;color:#627980}
@media(max-width:480px){.procedure-card{padding:16px}.procedure-card h2{font-size:23px}.procedure-details{padding:10px}}
@media print{.procedure-card{border:0;background:white;padding:0}.procedure-basis{border:1px solid #bbb}.procedure-checklist li{break-inside:avoid}.procedure-steps>li{break-inside:auto}}
`;
