const EN = {
  label: "Make a Procedure", prompt: "Turn this software walkthrough into a reusable procedure with prerequisites, exact settings, ordered steps, success checks, and clearly marked missing details.",
  procedure: "Software procedure", outcome: "What you will achieve", environment: "Software and version", prerequisites: "Before you start", steps: "Follow the steps", details: "Settings and commands", check: "Success check", gaps: "Details to resolve", video: "From the video", inferred: "Suggested · verify", unknown: "Not established", review: "Check missing details and suggested checks before following this procedure. It has not been executed or verified against current software.",
  checklist: "Reusable checklist", checklistHelp: "Use the boxes for this session, or copy and print the checklist. Checkmarks reset when the report is reopened.",
  sampling: "Examines up to 120 frames, with extra attention around instructional captions. Brief settings may still be missed. Supports software walkthroughs on YouTube and local videos.",
  cost: "Procedure: up to 120 frames, included in one managed report. Own-key costs depend on video length and usage.",
  unsupported: "Make a Procedure currently supports YouTube and local software walkthroughs.",
  noProcedure: "No usable software procedure could be extracted. Try a walkthrough that shows concrete software steps.",
  noFrames: "Too few software frames could be analyzed. Please retry with a clearer video.",
};
export type ProcedureCopy = typeof EN;
const rows: Record<string, string[]> = {
  'zh-CN': ['生成操作流程','软件操作流程','预期目标','软件和版本','开始前的准备','操作步骤','设置和命令','结果检查','待确认信息','来自视频','建议 · 请核实','尚未确定','请先核实缺失信息和建议的检查项。本流程未实际执行，也未针对当前软件验证。','可复用清单','勾选仅用于本次阅读；也可复制或打印清单。重新打开报告时勾选会重置。'],
  'zh-TW': ['建立操作流程','軟體操作流程','預期目標','軟體與版本','開始前的準備','操作步驟','設定與命令','結果檢查','待確認資訊','來自影片','建議 · 請確認','尚未確定','請先確認缺少的資訊與建議檢查項。本流程未實際執行，也未針對目前軟體驗證。','可重複使用的清單','勾選僅用於本次閱讀；也可複製或列印清單。重新開啟報告時勾選會重設。'],
  es: ['Crear un procedimiento','Procedimiento de software','Qué vas a lograr','Software y versión','Antes de empezar','Sigue los pasos','Configuración y comandos','Comprobación del resultado','Detalles por resolver','Del video','Sugerencia · verificar','Sin confirmar','Revisa los datos faltantes y las comprobaciones sugeridas. Este procedimiento no se ha ejecutado ni verificado con el software actual.','Lista reutilizable','Marca las casillas durante esta sesión, o copia e imprime la lista. Las marcas se reinician al volver a abrir el informe.'],
  ro: ['Creează o procedură','Procedură software','Ce vei realiza','Software și versiune','Înainte de a începe','Urmează pașii','Setări și comenzi','Verificarea rezultatului','Detalii de clarificat','Din videoclip','Sugestie · verifică','Neconfirmat','Verifică detaliile lipsă și verificările sugerate. Procedura nu a fost executată sau verificată cu versiunea actuală a software-ului.','Listă reutilizabilă','Bifează pentru această sesiune sau copiază și imprimă lista. Bifele se resetează la redeschiderea raportului.'],
  hi: ['प्रक्रिया बनाएं','सॉफ़्टवेयर प्रक्रिया','आप क्या हासिल करेंगे','सॉफ़्टवेयर और संस्करण','शुरू करने से पहले','चरणों का पालन करें','सेटिंग और कमांड','परिणाम की जांच','पुष्टि करने योग्य विवरण','वीडियो से','सुझाव · सत्यापित करें','पुष्टि नहीं हुई','छूटी जानकारी और सुझाई गई जांच की पुष्टि करें। इस प्रक्रिया को चलाया नहीं गया है और वर्तमान सॉफ़्टवेयर पर सत्यापित नहीं किया गया है।','दोबारा उपयोग की सूची','इस सत्र में बॉक्स चुनें या सूची कॉपी करके प्रिंट करें। रिपोर्ट दोबारा खोलने पर निशान रीसेट होंगे।'],
  fr: ['Créer une procédure','Procédure logicielle','Résultat attendu','Logiciel et version','Avant de commencer','Suivre les étapes','Paramètres et commandes','Vérification du résultat','Points à clarifier','Dans la vidéo','Suggestion · à vérifier','Non établi','Vérifiez les détails manquants et les contrôles suggérés. Cette procédure n’a pas été exécutée ni vérifiée avec le logiciel actuel.','Liste réutilisable','Cochez les cases pour cette session, ou copiez et imprimez la liste. Les coches sont réinitialisées à la réouverture du rapport.'],
  de: ['Anleitung erstellen','Software-Anleitung','Ziel','Software und Version','Vor dem Start','Schritte ausführen','Einstellungen und Befehle','Ergebnis prüfen','Offene Details','Aus dem Video','Vorschlag · prüfen','Nicht belegt','Prüfen Sie fehlende Angaben und vorgeschlagene Kontrollen. Diese Anleitung wurde nicht ausgeführt oder mit aktueller Software überprüft.','Wiederverwendbare Checkliste','Markieren Sie die Kästchen für diese Sitzung oder kopieren und drucken Sie die Liste. Beim erneuten Öffnen werden die Markierungen zurückgesetzt.'],
  'pt-BR': ['Criar procedimento','Procedimento de software','O que você vai alcançar','Software e versão','Antes de começar','Siga os passos','Configurações e comandos','Verificação do resultado','Detalhes a resolver','Do vídeo','Sugestão · verificar','Não confirmado','Verifique os detalhes ausentes e as verificações sugeridas. Este procedimento não foi executado nem validado com o software atual.','Lista reutilizável','Marque as caixas nesta sessão ou copie e imprima a lista. As marcas são redefinidas ao reabrir o relatório.'],
  ja: ['手順を作成','ソフトウェアの操作手順','達成すること','ソフトウェアとバージョン','始める前に','操作手順','設定とコマンド','結果の確認','確認が必要な点','動画に基づく','提案・要確認','未確認','不足情報と提案された確認項目を確認してください。この手順は実行されておらず、現在のソフトウェアでの検証も行われていません。','再利用できるチェックリスト','このセッションでチェックするか、コピーして印刷できます。レポートを開き直すとチェックはリセットされます。'],
  ko: ['절차 만들기','소프트웨어 사용 절차','달성할 목표','소프트웨어 및 버전','시작하기 전에','단계 따라 하기','설정 및 명령어','결과 확인','확인이 필요한 사항','동영상 근거','제안 · 확인 필요','확인되지 않음','누락된 정보와 제안된 확인 항목을 검토하세요. 이 절차는 실행되거나 현재 소프트웨어에서 검증되지 않았습니다.','재사용 체크리스트','이번 세션에서 체크하거나 목록을 복사해 인쇄하세요. 보고서를 다시 열면 체크 표시가 초기화됩니다.'],
};
const keys = ['label','procedure','outcome','environment','prerequisites','steps','details','check','gaps','video','inferred','unknown','review','checklist','checklistHelp'] as const;
const ui: Record<string, Partial<ProcedureCopy>> = {
  'zh-CN': {prompt:'将软件教程整理为可复用流程，包含准备事项、准确设置、步骤、结果检查和缺失信息。',sampling:'最多分析120帧，并重点关注操作说明附近的字幕。短暂出现的设置仍可能遗漏。支持YouTube和本地软件教程。',cost:'操作流程：最多120帧，计为一份托管报告。自有密钥费用取决于时长和用量。',unsupported:'目前仅支持YouTube和本地软件教程。',noProcedure:'未能提取可用的软件流程。请尝试展示具体操作步骤的教程。',noFrames:'可分析的软件画面太少。请使用更清晰的视频重试。'},
  'zh-TW': {prompt:'將軟體教學整理為可重複使用的流程，包含準備事項、精確設定、步驟、結果檢查與缺少的資訊。',sampling:'最多分析120幀，並重點關注操作說明附近的字幕。短暫出現的設定仍可能遺漏。支援YouTube與本機軟體教學。',cost:'操作流程：最多120幀，計為一份託管報告。自有金鑰費用取決於片長與用量。',unsupported:'目前僅支援YouTube與本機軟體教學。',noProcedure:'無法擷取可用的軟體流程。請嘗試展示具體操作步驟的教學。',noFrames:'可分析的軟體畫面太少。請使用更清晰的影片重試。'},
  es: {prompt:'Convierte este tutorial de software en un procedimiento reutilizable con requisitos, ajustes exactos, pasos, comprobaciones y detalles faltantes.',sampling:'Examina hasta 120 fotogramas y presta atención a los subtítulos de instrucciones. Algunos ajustes breves pueden omitirse. Admite tutoriales de YouTube y archivos locales.',cost:'Procedimiento: hasta 120 fotogramas, incluidos en un informe administrado. El costo con tu propia clave depende de la duración y el uso.',unsupported:'Actualmente se admiten tutoriales de software de YouTube y archivos locales.',noProcedure:'No se pudo extraer un procedimiento de software útil. Prueba un tutorial con pasos concretos.',noFrames:'Se pudieron analizar muy pocos fotogramas. Prueba con un video más claro.'},
  ro: {prompt:'Transformă acest tutorial software într-o procedură reutilizabilă cu cerințe, setări exacte, pași, verificări și detalii lipsă.',sampling:'Analizează până la 120 de cadre, cu atenție suplimentară la subtitrările cu instrucțiuni. Setările afișate scurt pot lipsi. Acceptă YouTube și videoclipuri locale.',cost:'Procedură: până la 120 de cadre, incluse într-un raport gestionat. Costul cu cheia proprie depinde de durată și utilizare.',unsupported:'Sunt acceptate tutoriale software de pe YouTube și videoclipuri locale.',noProcedure:'Nu s-a putut extrage o procedură software utilă. Încearcă un tutorial cu pași concreți.',noFrames:'Au fost analizate prea puține cadre. Reîncearcă folosind un videoclip mai clar.'},
  hi: {prompt:'इस सॉफ़्टवेयर ट्यूटोरियल को आवश्यकताओं, सटीक सेटिंग, क्रमबद्ध चरणों, परिणाम जांच और छूटी जानकारी वाली पुनः उपयोग योग्य प्रक्रिया में बदलें।',sampling:'अधिकतम120 फ़्रेम देखता है और निर्देश वाले कैप्शन पर अधिक ध्यान देता है। थोड़ी देर दिखने वाली सेटिंग छूट सकती हैं। YouTube और स्थानीय वीडियो समर्थित हैं।',cost:'प्रक्रिया: अधिकतम120 फ़्रेम, एक प्रबंधित रिपोर्ट में शामिल। अपनी कुंजी की लागत अवधि और उपयोग पर निर्भर है।',unsupported:'फ़िलहाल YouTube और स्थानीय सॉफ़्टवेयर ट्यूटोरियल समर्थित हैं।',noProcedure:'उपयोगी सॉफ़्टवेयर प्रक्रिया नहीं मिली। ठोस चरण दिखाने वाला ट्यूटोरियल आज़माएं।',noFrames:'बहुत कम फ़्रेम का विश्लेषण हो पाया। अधिक स्पष्ट वीडियो से फिर कोशिश करें।'},
};
export function procedureCopy(language?: string | null): ProcedureCopy {
  const tag = (language || 'en').replace(/_/g,'-');
  const key = /^zh-(TW|HK|Hant)/i.test(tag) ? 'zh-TW' : /^zh/i.test(tag) ? 'zh-CN' : /^pt/i.test(tag) ? 'pt-BR' : tag.split('-')[0];
  return {...EN, ...(rows[key] ? Object.fromEntries(keys.map((k,i)=>[k,rows[key][i]])) : {}), ...ui[key]};
}
