const EN = {
  label: "Recipe (preview)", prompt: "Turn this cooking video into a recipe, with ingredients, quantities, and steps. Clearly label estimates and missing details.",
  recipe: "Reconstructed recipe", ingredients: "Ingredients", amount: "Amount", steps: "Method", equipment: "Equipment",
  servings: "Servings", prepTime: "Prep time", cookTime: "Cook time", duration: "Time", temperature: "Temperature",
  video: "From the video", creator: "Creator description", reference: "Online source", estimate: "Suggested estimate", unknown: "Unknown",
  gaps: "Details to check", sources: "Sources", review: "Check estimates and missing details before cooking. This reconstruction has not been kitchen-tested.",
  lookup: "Look online for missing details", lookupHelp: "Optional. Sends the video title, URL, creator description, and extracted recipe details to OpenAI web search through your chosen AI access. Search queries may reach search providers. Your own key incurs additional search charges.",
  sampling: "Recipe mode examines up to 120 frames, starting at two per second. Longer clips use wider spacing.",
  researching: "Looking for recipe sources…", not_requested: "No online lookup used.", completed: "Online sources were consulted; borrowed details remain labeled.", unavailable: "Online lookup was unavailable or returned no cited sources. Missing details remain unverified.",
  cost: "Recipe preview: up to 120 frames. Online lookup is optional. Own-key costs depend on the clip and search usage.",
};
export type RecipeCopy = typeof EN;
const COPIES: Record<string, Partial<RecipeCopy>> = {
  "zh-CN": { label: "食谱（预览）", prompt: "将烹饪视频整理为食谱，包含食材、用量和步骤，并明确标注估算值和缺失信息。", recipe: "重建食谱", ingredients: "食材", amount: "用量", steps: "做法", equipment: "用具", servings: "份数", prepTime: "准备时间", cookTime: "烹饪时间", duration: "时间", temperature: "温度", video: "来自视频", creator: "创作者说明", reference: "网络来源", estimate: "建议估算", unknown: "未知", gaps: "待确认信息", sources: "来源", review: "烹饪前请确认估算和缺失信息。本食谱尚未经过实际烹饪测试。", lookup: "上网查找缺失信息", lookupHelp: "可选。通过您选择的 AI 连接，将视频标题、网址、创作者说明和提取的食谱信息发送给 OpenAI 网络搜索。查询可能发送给搜索服务商。使用自己的密钥会产生额外搜索费用。", sampling: "食谱模式最多分析 120 帧，起始为每秒两帧。较长的视频会增大取样间隔。", researching: "正在查找食谱来源…", not_requested: "未使用网络搜索。", completed: "已参考网络来源；借用的信息仍会标注。", unavailable: "网络搜索不可用或未返回带引用的来源。缺失信息仍未验证。", cost: "食谱预览：最多 120 帧，可选择网络搜索。自有密钥的费用取决于视频和搜索用量。" },
  "zh-TW": { label: "食譜（預覽）", prompt: "將烹飪影片整理為食譜，包含食材、用量和步驟，並明確標示估算值和缺少的資訊。", recipe: "重建食譜", ingredients: "食材", amount: "用量", steps: "做法", equipment: "用具", servings: "份數", prepTime: "準備時間", cookTime: "烹飪時間", duration: "時間", temperature: "溫度", video: "來自影片", creator: "創作者說明", reference: "網路來源", estimate: "建議估算", unknown: "未知", gaps: "待確認資訊", sources: "來源", review: "烹飪前請確認估算和缺少的資訊。本食譜尚未經過實際烹飪測試。", lookup: "上網查找缺少的資訊", lookupHelp: "選用。透過您選擇的 AI 連線，將影片標題、網址、創作者說明和擷取的食譜資訊傳送給 OpenAI 網路搜尋。查詢可能傳送給搜尋服務商。使用自己的金鑰會產生額外搜尋費用。", sampling: "食譜模式最多分析 120 幀，起始為每秒兩幀。較長的影片會增加取樣間隔。", researching: "正在查找食譜來源…", not_requested: "未使用網路搜尋。", completed: "已參考網路來源；借用的資訊仍會標示。", unavailable: "網路搜尋無法使用或未傳回附引用的來源。缺少的資訊仍未驗證。", cost: "食譜預覽：最多 120 幀，可選擇網路搜尋。自有金鑰的費用取決於影片和搜尋用量。" },
  es: { label: "Receta (vista previa)", prompt: "Convierte este video de cocina en una receta con ingredientes, cantidades y pasos. Indica las estimaciones y los datos faltantes.", recipe: "Receta reconstruida", ingredients: "Ingredientes", amount: "Cantidad", steps: "Preparación", equipment: "Utensilios", servings: "Porciones", prepTime: "Tiempo de preparación", cookTime: "Tiempo de cocción", duration: "Tiempo", temperature: "Temperatura", video: "Del video", creator: "Descripción del creador", reference: "Fuente en línea", estimate: "Estimación sugerida", unknown: "Desconocido", gaps: "Detalles por verificar", sources: "Fuentes", review: "Verifica las estimaciones y los datos faltantes antes de cocinar. Esta reconstrucción no se ha probado en cocina.", lookup: "Buscar datos faltantes en internet", lookupHelp: "Opcional. Envía el título, URL, descripción del creador y datos extraídos a la búsqueda web de OpenAI mediante tu acceso de IA. Las consultas pueden llegar a proveedores de búsqueda. Usar tu propia clave genera cargos adicionales por búsqueda.", sampling: "El modo receta examina hasta 120 fotogramas, comenzando con dos por segundo. Los videos más largos usan intervalos mayores.", researching: "Buscando fuentes de la receta…", not_requested: "No se utilizó búsqueda en línea.", completed: "Se consultaron fuentes en línea; los datos tomados de ellas siguen identificados.", unavailable: "La búsqueda no estuvo disponible o no devolvió fuentes citadas. Los datos faltantes siguen sin verificar.", cost: "Vista previa de recetas: hasta 120 fotogramas. Búsqueda en línea opcional. El costo con tu clave depende del video y de las búsquedas." },
  ro: { label: "Rețetă (previzualizare)", prompt: "Transformă acest videoclip culinar într-o rețetă cu ingrediente, cantități și pași. Marchează estimările și informațiile lipsă.", recipe: "Rețetă reconstruită", ingredients: "Ingrediente", amount: "Cantitate", steps: "Mod de preparare", equipment: "Ustensile", servings: "Porții", prepTime: "Timp de pregătire", cookTime: "Timp de gătire", duration: "Timp", temperature: "Temperatură", video: "Din videoclip", creator: "Descrierea creatorului", reference: "Sursă online", estimate: "Estimare sugerată", unknown: "Necunoscut", gaps: "Detalii de verificat", sources: "Surse", review: "Verifică estimările și informațiile lipsă înainte de a găti. Această reconstituire nu a fost testată în bucătărie.", lookup: "Caută online informațiile lipsă", lookupHelp: "Opțional. Trimite titlul, adresa URL, descrierea creatorului și detaliile extrase către căutarea web OpenAI prin accesul AI ales. Interogările pot ajunge la furnizori de căutare. Cheia proprie implică taxe suplimentare de căutare.", sampling: "Modul rețetă examinează până la 120 de cadre, pornind de la două pe secundă. Videoclipurile mai lungi folosesc intervale mai mari.", researching: "Se caută surse pentru rețetă…", not_requested: "Nu s-a folosit căutarea online.", completed: "Au fost consultate surse online; detaliile împrumutate rămân marcate.", unavailable: "Căutarea nu a fost disponibilă sau nu a returnat surse citate. Informațiile lipsă rămân neverificate.", cost: "Previzualizare rețetă: până la 120 de cadre. Căutare online opțională. Costul cu cheia proprie depinde de videoclip și căutări." },
  hi: { label: "रेसिपी (पूर्वावलोकन)", prompt: "इस खाना बनाने के वीडियो से सामग्री, मात्रा और चरणों वाली रेसिपी बनाएं। अनुमानों और छूटी जानकारी को स्पष्ट करें।", recipe: "वीडियो से तैयार रेसिपी", ingredients: "सामग्री", amount: "मात्रा", steps: "विधि", equipment: "उपकरण", servings: "परोसने की संख्या", prepTime: "तैयारी का समय", cookTime: "पकाने का समय", duration: "समय", temperature: "तापमान", video: "वीडियो से", creator: "निर्माता का विवरण", reference: "ऑनलाइन स्रोत", estimate: "सुझाया गया अनुमान", unknown: "अज्ञात", gaps: "जांचने योग्य विवरण", sources: "स्रोत", review: "पकाने से पहले अनुमानों और छूटी जानकारी की जांच करें। इस रेसिपी को रसोई में परखा नहीं गया है।", lookup: "छूटी जानकारी ऑनलाइन खोजें", lookupHelp: "वैकल्पिक। चुने गए AI कनेक्शन से वीडियो का शीर्षक, URL, निर्माता का विवरण और निकाली गई रेसिपी OpenAI वेब खोज को भेजता है। प्रश्न खोज प्रदाताओं तक जा सकते हैं। अपनी कुंजी से खोज के अतिरिक्त शुल्क लगते हैं।", sampling: "रेसिपी मोड अधिकतम 120 फ़्रेम देखता है, शुरुआत दो फ़्रेम प्रति सेकंड से होती है। लंबे वीडियो में अंतराल बढ़ता है।", researching: "रेसिपी के स्रोत खोजे जा रहे हैं…", not_requested: "ऑनलाइन खोज का उपयोग नहीं किया गया।", completed: "ऑनलाइन स्रोत देखे गए; उनसे लिए गए विवरण चिह्नित हैं।", unavailable: "ऑनलाइन खोज उपलब्ध नहीं थी या उद्धृत स्रोत नहीं मिले। छूटी जानकारी अभी सत्यापित नहीं है।", cost: "रेसिपी पूर्वावलोकन: अधिकतम 120 फ़्रेम। ऑनलाइन खोज वैकल्पिक है। अपनी कुंजी की लागत वीडियो और खोज पर निर्भर है।" },
  fr: { label: "Recette (aperçu)", recipe: "Recette reconstituée", ingredients: "Ingrédients", amount: "Quantité", steps: "Préparation", equipment: "Ustensiles", servings: "Portions", prepTime: "Préparation", cookTime: "Cuisson", duration: "Durée", temperature: "Température", video: "Dans la vidéo", creator: "Description du créateur", reference: "Source en ligne", estimate: "Estimation proposée", unknown: "Inconnu", gaps: "Points à vérifier", sources: "Sources", review: "Vérifiez les estimations et les informations manquantes avant de cuisiner. Cette reconstitution n’a pas été testée en cuisine.", not_requested: "Aucune recherche en ligne.", completed: "Des sources en ligne ont été consultées ; les informations empruntées sont signalées.", unavailable: "Recherche indisponible ou sans sources citées. Les informations manquantes restent à vérifier." },
  de: { label: "Rezept (Vorschau)", recipe: "Rekonstruiertes Rezept", ingredients: "Zutaten", amount: "Menge", steps: "Zubereitung", equipment: "Utensilien", servings: "Portionen", prepTime: "Vorbereitungszeit", cookTime: "Garzeit", duration: "Zeit", temperature: "Temperatur", video: "Aus dem Video", creator: "Beschreibung des Urhebers", reference: "Onlinequelle", estimate: "Vorgeschlagene Schätzung", unknown: "Unbekannt", gaps: "Zu prüfende Angaben", sources: "Quellen", review: "Prüfen Sie Schätzungen und fehlende Angaben vor dem Kochen. Diese Rekonstruktion wurde nicht in der Küche getestet.", not_requested: "Keine Onlinesuche verwendet.", completed: "Onlinequellen wurden herangezogen; übernommene Angaben bleiben gekennzeichnet.", unavailable: "Onlinesuche nicht verfügbar oder ohne zitierte Quellen. Fehlende Angaben bleiben ungeprüft." },
  "pt-BR": { label: "Receita (prévia)", recipe: "Receita reconstruída", ingredients: "Ingredientes", amount: "Quantidade", steps: "Modo de preparo", equipment: "Utensílios", servings: "Porções", prepTime: "Tempo de preparo", cookTime: "Tempo de cozimento", duration: "Tempo", temperature: "Temperatura", video: "Do vídeo", creator: "Descrição do criador", reference: "Fonte online", estimate: "Estimativa sugerida", unknown: "Desconhecido", gaps: "Detalhes a verificar", sources: "Fontes", review: "Verifique estimativas e informações ausentes antes de cozinhar. Esta reconstrução não foi testada na cozinha.", not_requested: "Nenhuma busca online utilizada.", completed: "Fontes online foram consultadas; detalhes emprestados continuam identificados.", unavailable: "Busca indisponível ou sem fontes citadas. As informações ausentes continuam sem verificação." },
  ja: { label: "レシピ（プレビュー）", recipe: "動画から再構成したレシピ", ingredients: "材料", amount: "分量", steps: "作り方", equipment: "調理器具", servings: "人数分", prepTime: "準備時間", cookTime: "調理時間", duration: "時間", temperature: "温度", video: "動画の情報", creator: "投稿者の説明", reference: "オンラインの情報源", estimate: "推定値", unknown: "不明", gaps: "確認が必要な点", sources: "情報源", review: "調理前に推定値と不足情報を確認してください。このレシピは調理テストを行っていません。", not_requested: "オンライン検索は使用していません。", completed: "オンライン情報源を参照しました。補った情報には表示があります。", unavailable: "検索を利用できないか、引用付きの情報源がありません。不足情報は未確認です。" },
  ko: { label: "레시피 (미리보기)", recipe: "영상으로 재구성한 레시피", ingredients: "재료", amount: "분량", steps: "조리 방법", equipment: "조리 도구", servings: "인분", prepTime: "준비 시간", cookTime: "조리 시간", duration: "시간", temperature: "온도", video: "영상에서 확인", creator: "제작자 설명", reference: "온라인 출처", estimate: "권장 추정치", unknown: "알 수 없음", gaps: "확인할 사항", sources: "출처", review: "조리 전에 추정치와 누락된 정보를 확인하세요. 이 레시피는 실제 조리로 검증되지 않았습니다.", not_requested: "온라인 검색을 사용하지 않았습니다.", completed: "온라인 출처를 참고했으며 가져온 정보는 표시되어 있습니다.", unavailable: "검색을 사용할 수 없거나 인용 출처가 없습니다. 누락된 정보는 확인되지 않았습니다." },
};

export function recipeCopy(language?: string | null): RecipeCopy {
  const tag = (language || "en").replace(/_/g, "-").toLowerCase();
  const key = tag.startsWith("zh") ? (/tw|hk|hant/.test(tag) ? "zh-TW" : "zh-CN") : tag.startsWith("pt") ? "pt-BR" : tag.split("-")[0];
  return { ...EN, ...COPIES[key] };
}
