// Markdown / JSON export of an analysis, mirroring the CLI's report writer.
import { fmtTs } from "./analyze";
import type { Analysis, QaEntry } from "./types";

export function toMarkdown(analysis: Analysis, qa: QaEntry[]): string {
  const lines: string[] = [];
  lines.push(`# VideoLens Report — ${analysis.source.title ?? "Untitled video"}`);
  lines.push("");
  lines.push(`- **Mode:** ${analysis.mode}`);
  lines.push(`- **Prompt:** ${analysis.prompt}`);
  if (analysis.source.url) lines.push(`- **Source:** ${analysis.source.url}`);
  if (analysis.source.durationSeconds) {
    lines.push(`- **Duration:** ${fmtTs(analysis.source.durationSeconds)}`);
  }
  lines.push(`- **Overall confidence:** ${analysis.confidence}`);
  lines.push("");

  lines.push("## Summary");
  lines.push("");
  lines.push(analysis.summary || "_(none)_");
  lines.push("");

  if (analysis.findings.length > 0) {
    lines.push("## Findings");
    lines.push("");
    for (const f of analysis.findings) {
      lines.push(`- **${f.finding}** _(${f.confidence})_`);
      for (const e of f.evidence) {
        lines.push(`  - \`[${fmtTs(e.timestamp)}]\` ${e.detail}`);
      }
    }
    lines.push("");
  }

  if (analysis.recommendations.length > 0) {
    lines.push("## Recommendations");
    lines.push("");
    analysis.recommendations.forEach((r, i) => {
      lines.push(`${i + 1}. **${r.recommendation}** _(${r.confidence})_`);
      if (r.rationale) lines.push(`   - ${r.rationale}`);
    });
    lines.push("");
  }

  if (analysis.tasks.length > 0) {
    lines.push("## Tasks");
    lines.push("");
    for (const t of analysis.tasks) {
      lines.push(`- [ ] ${t.title}${t.detail ? ` — ${t.detail}` : ""}`);
    }
    lines.push("");
  }

  if (analysis.limitations.length > 0) {
    lines.push("## Limitations");
    lines.push("");
    for (const lim of analysis.limitations) lines.push(`- ${lim}`);
    lines.push("");
  }

  if (qa.length > 0) {
    lines.push("## Q&A");
    lines.push("");
    for (const entry of qa) {
      lines.push(`**Q: ${entry.question}**`);
      lines.push("");
      lines.push(entry.answer);
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("_Generated by [VideoLens](https://videolens.io)_");
  return lines.join("\n");
}

export function download(filename: string, content: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}
