// Portable report exports. HTML reports are completely self-contained: no
// remote fonts, scripts, images, or VideoLens server are required.
import { fmtTs } from "./analyze";
import { MODE_PROMPTS } from "./modes";
import type { Analysis, Evidence, QaEntry } from "./types";

export function toMarkdown(analysis: Analysis, qa: QaEntry[]): string {
  const lines: string[] = [];
  lines.push(`# VideoLens Report — ${analysis.source.title ?? "Untitled video"}`);
  lines.push("");
  lines.push(`- **Report style:** ${MODE_PROMPTS[analysis.mode].label}`);
  lines.push(`- **Prompt:** ${analysis.prompt}`);
  if (analysis.source.url) lines.push(`- **Source:** ${analysis.source.url}`);
  if (analysis.source.durationSeconds) lines.push(`- **Duration:** ${fmtTs(analysis.source.durationSeconds)}`);
  lines.push(`- **Overall confidence:** ${analysis.confidence}`);
  lines.push("");
  lines.push("## Executive summary", "", analysis.summary || "_(none)_", "");

  if (analysis.findings.length > 0) {
    lines.push("## Key findings", "");
    for (const f of analysis.findings) {
      lines.push(`- **${f.finding}** _(${f.confidence} confidence)_`);
      for (const e of f.evidence) lines.push(`  - \`[${fmtTs(e.timestamp)}]\` ${e.detail}`);
    }
    lines.push("");
  }

  if (analysis.recommendations.length > 0) {
    lines.push("## Recommendations", "");
    analysis.recommendations.forEach((r, i) => {
      lines.push(`${i + 1}. **${r.recommendation}** _(${r.confidence} confidence)_`);
      if (r.rationale) lines.push(`   - ${r.rationale}`);
    });
    lines.push("");
  }

  if (analysis.tasks.length > 0) {
    lines.push("## Action items", "");
    for (const t of analysis.tasks) lines.push(`- [ ] ${t.title}${t.detail ? ` — ${t.detail}` : ""}`);
    lines.push("");
  }

  if (analysis.limitations.length > 0) {
    lines.push("## Limitations", "");
    for (const lim of analysis.limitations) lines.push(`- ${lim}`);
    lines.push("");
  }

  if (qa.length > 0) {
    lines.push("## Follow-up Q&A", "");
    for (const entry of qa) lines.push(`**Q: ${entry.question}**`, "", entry.answer, "");
  }

  lines.push("---", "_Generated by [VideoLens](https://videolens.io)_");
  return lines.join("\n");
}

export function toHtmlReport(analysis: Analysis, qa: QaEntry[]): string {
  const title = analysis.source.title ?? "Untitled video";
  const style = MODE_PROMPTS[analysis.mode].label;
  const generated = new Intl.DateTimeFormat(undefined, {
    year: "numeric", month: "long", day: "numeric", hour: "numeric", minute: "2-digit",
  }).format(new Date());
  const source = analysis.source.url
    ? `<a class="source-link" href="${attr(analysis.source.url)}" target="_blank" rel="noreferrer">Open original video <span aria-hidden="true">↗</span></a>`
    : `<span class="source-link muted">Local video file</span>`;

  const findings = analysis.findings.map((finding, index) => `
    <article class="finding avoid-break">
      <div class="finding-number">${String(index + 1).padStart(2, "0")}</div>
      <div class="finding-body">
        <div class="finding-heading"><h3>${html(finding.finding)}</h3>${confidenceBadge(finding.confidence)}</div>
        <div class="evidence-list">${finding.evidence.map((item) => evidenceRow(item, analysis.source.url)).join("")}</div>
      </div>
    </article>`).join("");

  const recommendations = analysis.recommendations.map((item, index) => `
    <li class="recommendation avoid-break">
      <span class="recommendation-index">${index + 1}</span>
      <div><div class="recommendation-title">${html(item.recommendation)} ${confidenceBadge(item.confidence)}</div>
      ${item.rationale ? `<p>${html(item.rationale)}</p>` : ""}</div>
    </li>`).join("");

  const tasks = analysis.tasks.map((task) => `
    <li class="task avoid-break"><span class="checkbox" aria-hidden="true"></span>
      <div><strong>${html(task.title)}</strong>${task.detail ? `<p>${html(task.detail)}</p>` : ""}</div>
    </li>`).join("");
  const limitations = analysis.limitations.map((item) => `<li>${html(item)}</li>`).join("");
  const questions = qa.map((entry) => `
    <article class="qa-entry avoid-break"><div class="qa-label">Question</div>
      <h3>${html(entry.question)}</h3><div class="qa-answer">${plainTextToHtml(entry.answer)}</div>
    </article>`).join("");

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light"><title>${html(title)} — VideoLens Report</title><style>${REPORT_CSS}</style></head>
<body><div class="page-shell">
  <header class="cover"><div class="cover-glow cover-glow-one"></div><div class="cover-glow cover-glow-two"></div>
    <div class="cover-content">
      <div class="brand-row"><div class="brand-mark"><span></span></div><div class="brand-word">VideoLens</div><div class="report-chip">AI VIDEO REPORT</div></div>
      <div class="eyebrow">${html(style)}</div><h1>${html(title)}</h1>
      <p class="cover-summary">${html(analysis.summary || "A timestamped, evidence-grounded report generated from the video.")}</p>
      <div class="cover-meta">
        <div><span>Duration</span><strong>${analysis.source.durationSeconds ? fmtTs(analysis.source.durationSeconds) : "Not available"}</strong></div>
        <div><span>Confidence</span><strong class="capitalize">${html(analysis.confidence)}</strong></div>
        <div><span>Prepared</span><strong>${html(generated)}</strong></div>
      </div><div class="cover-source">${source}</div>
    </div>
  </header>
  <main>
    <section class="executive-section"><div class="section-kicker">01 · Overview</div>
      <div class="executive-grid"><h2>Executive<br>summary</h2><div>
        <p class="executive-copy">${html(analysis.summary || "No summary was returned.")}</p>
        <div class="prompt-box"><span>Analysis brief</span>${html(analysis.prompt)}</div>
      </div></div>
    </section>
    ${analysis.findings.length > 0 ? `<section><div class="section-heading"><div><div class="section-kicker">02 · Evidence</div><h2>Key findings</h2></div><div class="section-count">${analysis.findings.length} findings</div></div><div class="findings">${findings}</div></section>` : ""}
    ${analysis.recommendations.length > 0 ? `<section><div class="section-heading"><div><div class="section-kicker">03 · Implications</div><h2>Recommendations</h2></div></div><ol class="recommendations">${recommendations}</ol></section>` : ""}
    ${analysis.tasks.length > 0 ? `<section><div class="section-heading"><div><div class="section-kicker">04 · Next steps</div><h2>Action items</h2></div></div><ul class="task-list">${tasks}</ul></section>` : ""}
    ${qa.length > 0 ? `<section><div class="section-heading"><div><div class="section-kicker">05 · Follow-up</div><h2>Questions &amp; answers</h2></div></div><div class="qa-list">${questions}</div></section>` : ""}
    ${analysis.limitations.length > 0 ? `<aside class="limitations avoid-break"><div class="limitations-title">Scope &amp; limitations</div><ul>${limitations}</ul></aside>` : ""}
  </main>
  <footer><div><strong>VideoLens</strong> · Video to written intelligence</div><div>Generated locally in your browser · videolens.io</div></footer>
</div></body></html>`;
}

export function reportFilename(analysis: Analysis, extension: string): string {
  const slug = (analysis.source.title ?? "video-report").normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "").slice(0, 64) || "video-report";
  return `${slug}-videolens.${extension}`;
}

export function printHtmlReport(analysis: Analysis, qa: QaEntry[]): boolean {
  const reportWindow = window.open("", "_blank");
  if (!reportWindow) return false;
  reportWindow.document.open();
  reportWindow.document.write(toHtmlReport(analysis, qa));
  reportWindow.document.close();
  reportWindow.focus();
  window.setTimeout(() => reportWindow.print(), 350);
  return true;
}

export function download(filename: string, content: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename; a.click();
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

function evidenceRow(item: Evidence, sourceUrl: string | null): string {
  const timestamp = fmtTs(item.timestamp);
  const url = sourceUrl ? timestampUrl(sourceUrl, item.timestamp) : null;
  const chip = url
    ? `<a class="timestamp" href="${attr(url)}" target="_blank" rel="noreferrer">${timestamp} ↗</a>`
    : `<span class="timestamp">${timestamp}</span>`;
  return `<div class="evidence-row">${chip}<p>${html(item.detail)}</p></div>`;
}

function timestampUrl(source: string, seconds: number): string | null {
  try {
    const url = new URL(source);
    if (url.hostname === "youtu.be" || url.hostname.endsWith("youtube.com")) {
      url.searchParams.set("t", `${Math.floor(seconds)}s`);
      return url.toString();
    }
  } catch { return null; }
  return null;
}

function confidenceBadge(confidence: Analysis["confidence"]): string {
  return `<span class="confidence confidence-${confidence}">${html(confidence)} confidence</span>`;
}

function plainTextToHtml(value: string): string {
  return value.split(/\n{2,}/).map((paragraph) => `<p>${html(paragraph).replace(/\n/g, "<br>")}</p>`).join("");
}

function html(value: string): string {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#039;");
}

function attr(value: string): string { return html(value); }

const REPORT_CSS = `
  :root { --ink:#111827; --muted:#64748b; --line:#dfe7ef; --paper:#fff; --soft:#f4f8fb; --cyan:#0891b2; --indigo:#4f46e5; --green:#047857; --amber:#b45309; --red:#b91c1c; }
  * { box-sizing:border-box; } html { background:#e9eff5; color:var(--ink); font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; }
  body { margin:0; -webkit-print-color-adjust:exact; print-color-adjust:exact; } .page-shell { width:min(100%,960px); margin:34px auto; background:var(--paper); box-shadow:0 24px 80px rgba(15,23,42,.14); }
  .cover { position:relative; min-height:570px; overflow:hidden; color:white; background:linear-gradient(138deg,#0b1223 0%,#111d3b 58%,#102a42 100%); }
  .cover::after { position:absolute; inset:0; opacity:.08; background-image:linear-gradient(rgba(255,255,255,.55) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.55) 1px,transparent 1px); background-size:40px 40px; content:""; }
  .cover-glow { position:absolute; border-radius:999px; filter:blur(4px); } .cover-glow-one { width:430px; height:430px; right:-150px; top:-180px; background:radial-gradient(circle,rgba(34,211,238,.45),rgba(34,211,238,0) 69%); }
  .cover-glow-two { width:440px; height:440px; left:-240px; bottom:-270px; background:radial-gradient(circle,rgba(99,102,241,.48),rgba(99,102,241,0) 68%); }
  .cover-content { position:relative; z-index:2; padding:54px 64px 52px; } .brand-row { display:flex; align-items:center; gap:11px; }
  .brand-mark { display:grid; place-items:center; width:31px; height:31px; border-radius:9px; background:linear-gradient(135deg,#06b6d4,#6366f1); }
  .brand-mark span { width:0; height:0; margin-left:2px; border-top:6px solid transparent; border-bottom:6px solid transparent; border-left:10px solid white; }
  .brand-word { font-size:18px; font-weight:760; letter-spacing:-.02em; } .report-chip { margin-left:auto; padding:7px 10px; border:1px solid rgba(255,255,255,.18); border-radius:999px; color:#b9c6d8; font-size:9px; font-weight:750; letter-spacing:.16em; }
  .eyebrow { margin-top:88px; color:#67e8f9; font-size:11px; font-weight:800; letter-spacing:.18em; text-transform:uppercase; }
  h1 { max-width:740px; margin:18px 0 20px; font-size:48px; line-height:1.04; letter-spacing:-.045em; } .cover-summary { max-width:705px; margin:0; color:#cbd5e1; font-size:17px; line-height:1.65; }
  .cover-meta { display:grid; grid-template-columns:.7fr .7fr 1.3fr; gap:24px; margin-top:54px; padding-top:25px; border-top:1px solid rgba(255,255,255,.14); }
  .cover-meta span { display:block; margin-bottom:6px; color:#7f91a9; font-size:9px; font-weight:750; letter-spacing:.13em; text-transform:uppercase; } .cover-meta strong { color:#f8fafc; font-size:12px; font-weight:650; }
  .capitalize { text-transform:capitalize; } .cover-source { margin-top:28px; } .source-link { color:#a5f3fc; font-size:12px; font-weight:700; text-decoration:none; } .source-link.muted { color:#94a3b8; }
  main { padding:0 64px 18px; } section { padding:62px 0; border-bottom:1px solid var(--line); } .section-kicker { margin-bottom:15px; color:var(--cyan); font-size:10px; font-weight:800; letter-spacing:.16em; text-transform:uppercase; }
  .executive-grid { display:grid; grid-template-columns:210px 1fr; gap:48px; } h2 { margin:0; font-size:32px; line-height:1.05; letter-spacing:-.035em; }
  .executive-copy { margin:0; color:#26364c; font-family:Georgia,"Times New Roman",serif; font-size:21px; line-height:1.65; }
  .prompt-box { margin-top:28px; padding:16px 18px; border-left:3px solid var(--cyan); color:#475569; background:var(--soft); font-size:12px; line-height:1.55; } .prompt-box span { display:block; margin-bottom:5px; color:#94a3b8; font-size:9px; font-weight:750; letter-spacing:.13em; text-transform:uppercase; }
  .section-heading { display:flex; align-items:end; justify-content:space-between; margin-bottom:34px; } .section-count { color:#94a3b8; font-size:11px; font-weight:650; text-transform:uppercase; letter-spacing:.08em; }
  .finding { display:grid; grid-template-columns:48px 1fr; gap:18px; padding:28px 0; border-top:1px solid var(--line); } .finding:first-child { border-top:0; padding-top:0; }
  .finding-number { padding-top:3px; color:#94a3b8; font-family:ui-monospace,SFMono-Regular,Menlo,monospace; font-size:11px; } .finding-heading { display:flex; align-items:flex-start; gap:14px; justify-content:space-between; }
  .finding h3 { margin:0; font-size:17px; line-height:1.45; letter-spacing:-.015em; } .confidence { display:inline-flex; flex:none; padding:4px 8px; border-radius:999px; font-size:8px; font-weight:800; letter-spacing:.07em; text-transform:uppercase; white-space:nowrap; vertical-align:2px; }
  .confidence-high { color:var(--green); background:#ecfdf5; } .confidence-medium { color:var(--amber); background:#fffbeb; } .confidence-low { color:var(--red); background:#fef2f2; }
  .evidence-list { margin-top:15px; } .evidence-row { display:grid; grid-template-columns:64px 1fr; gap:12px; align-items:start; margin-top:9px; } .evidence-row p { margin:0; color:#64748b; font-size:12px; line-height:1.55; }
  .timestamp { display:inline-block; width:max-content; padding:4px 7px; border-radius:5px; color:#0e7490; background:#ecfeff; font-family:ui-monospace,SFMono-Regular,Menlo,monospace; font-size:9px; font-weight:750; text-decoration:none; }
  .recommendations { display:grid; grid-template-columns:1fr 1fr; gap:14px; margin:0; padding:0; list-style:none; } .recommendation { display:grid; grid-template-columns:32px 1fr; gap:13px; padding:20px; border:1px solid var(--line); border-radius:13px; background:linear-gradient(145deg,#fff,#f8fafc); }
  .recommendation-index { display:grid; place-items:center; width:28px; height:28px; border-radius:8px; color:white; background:linear-gradient(135deg,var(--cyan),var(--indigo)); font-size:11px; font-weight:800; }
  .recommendation-title { font-size:13px; font-weight:760; line-height:1.45; } .recommendation p,.task p { margin:7px 0 0; color:#64748b; font-size:11px; line-height:1.5; }
  .task-list { margin:0; padding:0; list-style:none; border:1px solid var(--line); border-radius:13px; overflow:hidden; } .task { display:grid; grid-template-columns:24px 1fr; gap:12px; padding:17px 19px; border-top:1px solid var(--line); } .task:first-child { border-top:0; }
  .task strong { font-size:13px; line-height:1.45; } .checkbox { width:17px; height:17px; margin-top:1px; border:1.5px solid #94a3b8; border-radius:5px; }
  .qa-entry { padding:24px; border:1px solid var(--line); border-radius:14px; margin-top:14px; } .qa-label { color:var(--cyan); font-size:9px; font-weight:800; letter-spacing:.13em; text-transform:uppercase; } .qa-entry h3 { margin:8px 0 14px; font-size:16px; }
  .qa-answer { color:#475569; font-size:12px; line-height:1.65; } .qa-answer p { margin:8px 0 0; } .limitations { margin:42px 0; padding:22px 24px; border:1px solid #fde68a; border-radius:13px; color:#78350f; background:#fffbeb; }
  .limitations-title { font-size:11px; font-weight:800; letter-spacing:.08em; text-transform:uppercase; } .limitations ul { margin:11px 0 0; padding-left:18px; } .limitations li { margin-top:5px; font-size:11px; line-height:1.5; }
  footer { display:flex; justify-content:space-between; padding:24px 64px; color:#94a3b8; background:#f8fafc; font-size:9px; letter-spacing:.03em; } footer strong { color:#475569; } .avoid-break { break-inside:avoid; page-break-inside:avoid; }
  @media (max-width:700px) { .page-shell { margin:0; } .cover-content,main { padding-left:28px; padding-right:28px; } h1 { font-size:36px; } .executive-grid { grid-template-columns:1fr; gap:22px; } .recommendations { grid-template-columns:1fr; } footer { padding:22px 28px; gap:16px; } }
  @page { size:A4; margin:13mm; } @media print { html { background:white; } .page-shell { width:auto; margin:0; box-shadow:none; } .cover { min-height:271mm; break-after:page; page-break-after:always; } .cover-content { padding:24mm 18mm; } .eyebrow { margin-top:38mm; } main { padding:0; } section { padding:13mm 2mm; } .section-heading { break-after:avoid-page; page-break-after:avoid; } .section-heading + * { break-before:avoid-page; page-break-before:avoid; } footer { padding:7mm 2mm 0; } a { color:inherit; text-decoration:none; } }
`;
