[theme]
base = "light"
primaryColor = "#0891B2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#0F172A"
font = "sans serif"

[server]
runOnSave = true
headless = false

[browser]
gatherUsageStats = false
